#include "CalcDialect.h"

using namespace mlir;
using namespace mlir::calc;

#include "CalcDialect.cpp.inc"

#define GET_OP_CLASSES
#include "CalcOps.cpp.inc"

// -----------------------------------------------------------------------------
// Canonicalization patterns generated from CalcPatterns.td.
// The include must be inside an anonymous namespace so the generated
// pattern classes don't conflict with anything else in the linker.
// -----------------------------------------------------------------------------
namespace {
#include "CalcCanonicalize.inc"
} // namespace

void CalcDialect::initialize() {
  addOperations<
#define GET_OP_LIST
#include "CalcOps.cpp.inc"
      >();
}

// =============================================================================
// TASK 4: implement materializeConstant().
//
// Required by `let hasConstantMaterializer = 1;` on the dialect.
// Signature:
//
//     Operation *CalcDialect::materializeConstant(
//         OpBuilder &builder, Attribute value, Type type, Location loc);
//
// Behaviour:
//   - cast `value` to IntegerAttr
//   - if it casts, build a ConstOp with that attribute and return it
//   - otherwise return nullptr (we can only materialize i32 constants)
//
// Hint:
//     if (auto intAttr = dyn_cast<IntegerAttr>(value))
//       return builder.create<ConstOp>(loc, type, intAttr);
//     return nullptr;
// =============================================================================

// TODO: implement `Operation *CalcDialect::materializeConstant(...)` here.

// -----------------------------------------------------------------------------
// Custom verifier for calc.shr.
//
// Returns success() if the op is well-formed, or emits a diagnostic
// and returns failure() if not. emitOpError() automatically prefixes
// the op's name and location.
// -----------------------------------------------------------------------------
LogicalResult ShrOp::verify() {
  // If the shift amount comes from a constant we can check statically,
  // ensure it fits in [0, 31]. Otherwise it's a dynamic value and we
  // can only trust the user (or hope a later pass folds it).
  auto cst = getAmount().getDefiningOp<ConstOp>();
  if (!cst)
    return success();

  uint32_t v = cst.getValue();
  if (v > 31)
    return emitOpError("shift amount must be in [0, 31], got ") << v;

  return success();
}

// -----------------------------------------------------------------------------
// Canonicalization hook: tell the canonicalizer which patterns to apply
// to each op. The pattern *names* (AddZero, MulOne, MulZero) are the
// `def NAME : Pat<...>` records from CalcPatterns.td, surfaced as C++
// classes by mlir-tblgen -gen-rewriters.
// -----------------------------------------------------------------------------
void AddOp::getCanonicalizationPatterns(RewritePatternSet &results,
                                        MLIRContext *context) {
  results.add<AddZero>(context);
}

void MulOp::getCanonicalizationPatterns(RewritePatternSet &results,
                                        MLIRContext *context) {
  results.add<MulOne, MulZero>(context);
}

// =============================================================================
// TASK 5: implement three fold methods.
//
// Each is generated by `let hasFolder = 1;` in ODS. Signature:
//
//     OpFoldResult Op::fold(FoldAdaptor adaptor);
//
// Return values:
//   - an Attribute    → result is replaced with a new constant op
//   - a Value         → result is replaced with that existing value
//   - {}              → fold failed, leave the IR alone
//
// Folds run inside --canonicalize. They run BEFORE patterns on a
// given op, so ConstOp's "fold to my value attribute" is what makes
// constants visible to downstream fold logic.
//
// Required implementations:
//
//   ConstOp::fold — return the op's value attribute, e.g.:
//
//       return adaptor.getValueAttr();
//
//     (Use getValueAttr(), not getValue(): getValue() returns uint32_t
//     because our ODS declares the value as I32Attr. OpFoldResult only
//     accepts Attribute or Value.)
//
//   AddOp::fold — if both operands are constants, return
//   IntegerAttr::get(getType(), lhs + rhs); else return {}.
//
//       IntegerAttr lhs, rhs;
//       if (!matchPattern(getLhs(), m_Constant(&lhs)) ||
//           !matchPattern(getRhs(), m_Constant(&rhs)))
//         return {};
//       return IntegerAttr::get(getType(), lhs.getInt() + rhs.getInt());
//
//   MulOp::fold — same shape, but multiply.
// =============================================================================

// TODO: implement ConstOp::fold, AddOp::fold, MulOp::fold here.
