#include "CalcDialect.h"
#include "CalcPasses.h"

#include "mlir/IR/DialectRegistry.h"
#include "mlir/InitAllDialects.h"
#include "mlir/InitAllPasses.h"
#include "mlir/Tools/mlir-opt/MlirOptMain.h"

int main(int argc, char **argv) {
  mlir::DialectRegistry registry;
  mlir::registerAllDialects(registry);
  mlir::registerAllPasses();
  registry.insert<mlir::calc::CalcDialect>();

  // TODO (Task 2) — call `mlir::calc::registerCalcPasses()` here.
  // That function is generated by `GEN_PASS_REGISTRATION` in
  // CalcPasses.h and registers every pass declared in CalcPasses.td.
  // Without this call, `--calc-strength-reduce` will not appear in
  // `--help` and will be rejected as an unknown flag.

  return mlir::asMainReturnCode(
      mlir::MlirOptMain(argc, argv, "calc-opt", registry));
}
