#include "CalcDialect.h"
#include "CalcPasses.h"

#include "mlir/IR/DialectRegistry.h"
#include "mlir/InitAllDialects.h"
#include "mlir/InitAllPasses.h"
#include "mlir/Tools/mlir-opt/MlirOptMain.h"

int main(int argc, char **argv) {
  mlir::DialectRegistry registry;
  mlir::registerAllDialects(registry);
  mlir::registerAllPasses();
  registry.insert<mlir::calc::CalcDialect>();

  // Register our custom passes. `registerCalcPasses` is generated by
  // `GEN_PASS_REGISTRATION` in CalcPasses.h and registers every pass
  // declared in CalcPasses.td under the name and constructor from ODS.
  mlir::calc::registerCalcPasses();

  return mlir::asMainReturnCode(
      mlir::MlirOptMain(argc, argv, "calc-opt", registry));
}
