#include "CalcPasses.h"

#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"

namespace mlir {
namespace calc {

// `GEN_PASS_DEF_<PASSNAME>` expands to the pass base class definition.
// The macro must come AFTER the include and BEFORE the pass class that
// inherits from `impl::CalcStrengthReduceBase`.
#define GEN_PASS_DEF_CALCSTRENGTHREDUCE
#include "CalcPasses.h.inc"

namespace {

// -----------------------------------------------------------------------------
// The rewrite pattern.
//
// An `OpRewritePattern<OpTy>` is a C++-side rewrite — like DRR but with
// arbitrary logic. The driver finds candidate `OpTy` ops in the IR and
// calls `matchAndRewrite` on each. Return `success()` to commit the
// rewrite; `failure()` to leave the op alone.
//
// Inside, `rewriter` is the *only* legal way to mutate IR: it tracks
// every edit so the driver can re-walk affected ops. Calling
// `op.erase()` or `builder.create<...>()` directly would bypass the
// rewriter and break the worklist.
// -----------------------------------------------------------------------------
struct MulByTwoToAdd : public OpRewritePattern<MulOp> {
  using OpRewritePattern<MulOp>::OpRewritePattern;

  LogicalResult matchAndRewrite(MulOp op,
                                PatternRewriter &rewriter) const override {
    // Commutative trait normalises constants to the RHS, so we only
    // need to check the RHS.
    IntegerAttr rhsAttr;
    if (!matchPattern(op.getRhs(), m_Constant(&rhsAttr)))
      return failure();
    if (rhsAttr.getInt() != 2)
      return failure();

    // `replaceOpWithNewOp<NewOp>(op, ...)` is the standard "replace this
    // op with a freshly built one" idiom. The new op's result inherits
    // the old op's uses; the old op is erased.
    rewriter.replaceOpWithNewOp<AddOp>(op, op.getType(), op.getLhs(),
                                       op.getLhs());
    return success();
  }
};

// -----------------------------------------------------------------------------
// The pass itself.
//
// `CalcStrengthReduceBase` is generated by `GEN_PASS_DEF_CALCSTRENGTHREDUCE`
// from the ODS def in CalcPasses.td. It implements pass plumbing
// (registration, name, options, statistics, ...). We only have to
// override `runOnOperation()`.
//
// `getOperation()` returns the op the pass is anchored on — in our case
// the `func::FuncOp` we declared in the .td. `applyPatternsAndFoldGreedily`
// runs our patterns plus all registered folds until a fixed point.
// -----------------------------------------------------------------------------
struct CalcStrengthReducePass
    : public impl::CalcStrengthReduceBase<CalcStrengthReducePass> {
  void runOnOperation() override {
    RewritePatternSet patterns(&getContext());
    patterns.add<MulByTwoToAdd>(&getContext());
    if (failed(applyPatternsAndFoldGreedily(getOperation(),
                                            std::move(patterns))))
      signalPassFailure();
  }
};

} // namespace

std::unique_ptr<Pass> createCalcStrengthReducePass() {
  return std::make_unique<CalcStrengthReducePass>();
}

} // namespace calc
} // namespace mlir
