#include "CalcDialect.h"

#include "llvm/ADT/TypeSwitch.h"
#include "mlir/IR/DialectImplementation.h"

using namespace mlir;
using namespace mlir::calc;

#include "CalcDialect.cpp.inc"

#define GET_TYPEDEF_CLASSES
#include "CalcTypes.cpp.inc"

#define GET_OP_CLASSES
#include "CalcOps.cpp.inc"

// -----------------------------------------------------------------------------
// Canonicalization patterns generated from CalcPatterns.td.
// The include must be inside an anonymous namespace so the generated
// pattern classes don't conflict with anything else in the linker.
// -----------------------------------------------------------------------------
namespace {
#include "CalcCanonicalize.inc"
} // namespace

void CalcDialect::initialize() {
  addOperations<
#define GET_OP_LIST
#include "CalcOps.cpp.inc"
      >();
  // Register our parameterised types alongside the operations. Without
  // this call the dialect can't parse `!calc.fixed<8, 8>` (and you'd
  // get "expected attribute value" errors at parse time).
  addTypes<
#define GET_TYPEDEF_LIST
#include "CalcTypes.cpp.inc"
      >();
}

// -----------------------------------------------------------------------------
// Custom verifier for !calc.fixed<int, frac>.
//
// Declared via `let genVerifyDecl = 1` in the TypeDef. The signature
// takes a diagnostic-emitter for reporting, then the parameter values
// in the order they appear in `parameters`.
// -----------------------------------------------------------------------------
LogicalResult
FixedType::verify(function_ref<InFlightDiagnostic()> emitError,
                  unsigned intBits, unsigned fracBits) {
  if (fracBits == 0)
    return emitError() << "fixed-point type must have at least 1 "
                          "fractional bit (use i" << intBits << " instead)";
  unsigned total = intBits + fracBits;
  if (total != 8 && total != 16 && total != 32 && total != 64)
    return emitError() << "intBits + fracBits must be 8, 16, 32, or 64; "
                          "got " << total;
  return success();
}

// -----------------------------------------------------------------------------
// materializeConstant — declared via `let hasConstantMaterializer = 1`.
//
// The fold-driven canonicalizer calls this when an op's fold() returns
// an Attribute: it asks "please create an op of `type` that carries this
// constant attribute." We answer by building a calc.const.
// -----------------------------------------------------------------------------
Operation *CalcDialect::materializeConstant(OpBuilder &builder, Attribute value,
                                            Type type, Location loc) {
  if (auto intAttr = dyn_cast<IntegerAttr>(value))
    return builder.create<ConstOp>(loc, type, intAttr);
  return nullptr;
}

// -----------------------------------------------------------------------------
// Custom verifier for calc.shr.
//
// Returns success() if the op is well-formed, or emits a diagnostic
// and returns failure() if not. emitOpError() automatically prefixes
// the op's name and location.
// -----------------------------------------------------------------------------
LogicalResult ShrOp::verify() {
  // If the shift amount comes from a constant we can check statically,
  // ensure it fits in [0, 31]. Otherwise it's a dynamic value and we
  // can only trust the user (or hope a later pass folds it).
  auto cst = getAmount().getDefiningOp<ConstOp>();
  if (!cst)
    return success();

  uint32_t v = cst.getValue();
  if (v > 31)
    return emitOpError("shift amount must be in [0, 31], got ") << v;

  return success();
}

// -----------------------------------------------------------------------------
// Canonicalization hook: tell the canonicalizer which patterns to apply
// to each op. The pattern *names* (AddZero, MulOne, MulZero) are the
// `def NAME : Pat<...>` records from CalcPatterns.td, surfaced as C++
// classes by mlir-tblgen -gen-rewriters.
// -----------------------------------------------------------------------------
void AddOp::getCanonicalizationPatterns(RewritePatternSet &results,
                                        MLIRContext *context) {
  results.add<AddZero>(context);
}

void MulOp::getCanonicalizationPatterns(RewritePatternSet &results,
                                        MLIRContext *context) {
  results.add<MulOne, MulZero>(context);
}

// -----------------------------------------------------------------------------
// Fold methods.
//
// `fold` is a complement to canonicalization patterns: instead of
// rewriting one op into a different op, it tries to produce a constant
// or existing value that the result can be replaced with.
//
// Signature (generated by `let hasFolder = 1`):
//
//     OpFoldResult Op::fold(FoldAdaptor adaptor);
//
// `FoldAdaptor` gives typed access to the op's *constant* operands.
// For an operand that came from a Pure op whose fold returned a
// constant attribute, the adaptor exposes that attribute; for any
// other operand, the adaptor returns null.
//
// Return values:
//   - an Attribute   → result is replaced with a new constant
//   - a Value        → result is replaced with that existing value
//   - {}             → fold failed, no replacement
//
// Folds run as part of --canonicalize (alongside DRR patterns).
// They run BEFORE patterns on a given op, so ConstOp's fold-to-attr
// is what makes operand attributes available to AddOp / MulOp folds.
// -----------------------------------------------------------------------------

// const folds trivially to its own attribute. This is what makes the
// constants "visible" to downstream folds of other ops.
//
// Note: we use `adaptor.getValueAttr()` (returns the IntegerAttr),
// NOT `adaptor.getValue()` — the latter returns the raw uint32_t
// because our `value` attribute is declared as I32Attr in ODS, and
// OpFoldResult only accepts an Attribute or a Value.
OpFoldResult ConstOp::fold(FoldAdaptor adaptor) {
  return adaptor.getValueAttr();
}

// add(const a, const b) → const(a + b)
OpFoldResult AddOp::fold(FoldAdaptor adaptor) {
  IntegerAttr lhs, rhs;
  if (!matchPattern(getLhs(), m_Constant(&lhs)) ||
      !matchPattern(getRhs(), m_Constant(&rhs)))
    return {};
  return IntegerAttr::get(getType(), lhs.getInt() + rhs.getInt());
}

// mul(const a, const b) → const(a * b)
OpFoldResult MulOp::fold(FoldAdaptor adaptor) {
  IntegerAttr lhs, rhs;
  if (!matchPattern(getLhs(), m_Constant(&lhs)) ||
      !matchPattern(getRhs(), m_Constant(&rhs)))
    return {};
  return IntegerAttr::get(getType(), lhs.getInt() * rhs.getInt());
}
